---
- name: Instalar Apache y php
  apt:
    name: "{{ item }}"
  with_items:
    - apache2
    - php7.0
    - php7.0-pgsql
    - libapache2-mod-php7.0
    - php-xml
    - php-gd
    - php7.0-mbstring
    - unzip

- name: Unzip drupal en el directorio del servidor apache
  unarchive: src=../../drupal/templates/zip dest=/var/www/

- name: Fichero del sitio web
  copy: src=../templates/drupal.conf dest=/etc/apache2/sites-available/drupal.conf

- name: Mover ficheros a directorio drupal
  shell: mv /var/www/drupal-8.6.7/* /var/www/drupal/ && sudo chown -R www-data:www-data /var/www/drupal/ 

- name: Activar virtualhost
  shell: a2ensite drupal.conf

- name: URL limpias
  shell: a2enmod rewrite
  notify:
    - restart apache2

