---
- name: Instalar Postgres
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql
    - python-psycopg2

- name: Crear base de datos drupal
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_database }}"

- name: Crear usuario drupal
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ db_database }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "ALL"
    expires: infinity

- name: Configuracion de la base de datos
  command: psql -c "ALTER DATABASE {{ db_database }} SET bytea_output = 'escape';"
  become: yes
  vars:
    ansible_ssh_pipelining: true

- name: Configuracion de acceso remoto
  copy: src=../templates/postgresql.conf dest=/etc/postgresql/9.6/main/postgresql.conf

- name: Configuracion de acceso remoto 2
  copy: src=../templates/pg_hba.conf dest=/etc/postgresql/9.6/main/pg_hba.conf
  notify:
    - restart postgresql

#- name: restart postgresql
#  service: 
#    name: postgresql
#    state: restarted
