---
- name: Instalacion de drupal
  hosts: all
  become: yes
  roles:
    - role: common

- hosts: nodo1
  become: yes
  roles:
    - role: postgres
    - role: bind9

- hosts: nodo2
  become: yes
  roles:
    - role: apache2
    - role: drupal
