- name: Download Drush
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.1.2/drush.phar
    dest: /usr/local/bin/drush
    mode: 0755
    owner: www-data
    group: www-data

- name: Install Drush
  command: >
    drush si standard -y
    --db-url=pgsql://{{ db_user }}:{{ db_password }}@{{ ip_nodo1 }}/{{ db_database }}
    --account-name=arias
    --account-pass=arias
    --account-mail=jesusariasgil1995@hotmail.com
    --site-name="Drupal" 
    -r /var/www/drupal -y

- name: Permisos drupal
  file:
    path: /var/www/drupal
    mode: 0755
    owner: www-data
    group: www-data
    recurse: yes

- name: Cargar CSS Drupal
  shell: drush cr -r /var/www/drupal/ 
  notify:
    - restart apache2
